services:
  - type: web
    name: resume-flask-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn serve:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: ENVIRONMENT
        value: production
      - key: OPENAI_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false 